export type {
  Article,
  ArticleStatus,
  MarketItem,
  MarketItemKind,
  ScrapeError,
  ScrapeLock,
  ScrapeJob,
  ScrapeRun,
  ScrapeRunStatus,
  ScrapeStage,
  ScrapeMethod,
  Source,
  SourceCategory,
} from "@prisma/client";
